watts = 'watts'
athlete_id = 'athlete_id'
athlete_name = 'athlete_name'
ride = "Ride"
activities = 'activities'
rowData = 'rowData'
activity = 'activity'
entity = 'entity'
location = "location"
activity_type = 'type'
activity_id = 'id'
html_parser = "html.parser"
average = 'Avg'
maxx = 'Max'
heart_rate = 'Heart Rate'
cadence = 'Cadence'
speed = 'Speed'
power = 'Power'
